mod client;
mod discovery;
pub use client::ClientInfo;
mod errors;
pub use errors::{authentication_error, authentication_summary};
mod frames;
mod session;
mod transport;
mod version;
pub use discovery::*;
pub use frames::*;
pub use transport::{Session, parse_pin};
pub const MAX_BODY: usize = 1024 * 1024;
pub type Tunnel = tokio_native_tls::TlsStream<tokio::net::TcpStream>;
